version: '3.9'

services:
  kong-gateway:
    build: ./kong

  mssql:
    build: ./mssql

  mongo:
    image: mongo:5.0.5

  postgres:
    build: ./postgres

  redis:
    image: redis:6.2.6-alpine

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine

  mailhog:
    image: mailhog/mailhog:v1.0.1

  catalog-service:
    build: ./services/catalog-service

  basket-service:
    build: ./services/basket-service

  review-service:
    build: ./services/review-service

  storage-service:
    build: ./services/storage-service

  vendor-service:
    build: ./services/vendor-service

  payment-service:
    build: ./services/payment-service

  currency-service:
    build: ./services/currency-service

  discount-service:
    build: ./services/discount-service

  coupon-service:
    build: ./services/coupon-service

  ordering-service:
    build: ./services/ordering-service

  notification-service:
    build: ./services/notification-service

  customer-web-client:
    build: ./clients/customer-web-client

  vendor-web-client:
    build: ./clients/vendor-web-client

  administration-web-client:
    build: ./clients/administration-web-client
